[package]
name = "evolutionary_alg"
version = "0.1.0"
authors = ["Erwin Bonsma <eriban@users.sourceforge.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
rand = "0.8.4"